spring.datasource.url=jdbc:mariadb://localhost:3306/mma_spain
spring.datasource.username=mma
spring.datasource.password=1234

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.thymeleaf.cache=false

server.port=8080